### ISSUE TITLE
Keen IO Junks data with KeenIOClient for Android

### ISSUE THREAD

**Issue by ericallard** [keenlabs/KeenClient-Android-Sample#2]
I have the same issue!

http://stackoverflow.com/questions/28096468/keen-io-junks-data-with-keenioclient-for-android

-Eric

**Comment by Geeber** [comment]
We've confirmed that this is a bug, and will get out a 2.1.1 patch ASAP. In the meantime if you're blocked we'd recommend rolling back to the 2.0.3 release.

**Comment by Geeber** [comment]
The 2.1.1 release is out, and the sample has been updated to depend on the new version. Please try pulling the latest code and testing again. Sorry for the mistake!
